### ISSUE TITLE
QTableWidgetitem error

### ISSUE THREAD

**Issue by biotech70** [pymodproject/pymod#10]
Hi
What is the cause of the uploaded error?
![Untitled](https://user-images.githubusercontent.com/73783725/183306695-ba41e36c-fb8c-4359-b3d3-6bbeb1fc7af4.png)

**Comment by paiardin** [comment]
Dear Mohammad,
thank you for your interest in PyMod3. Could you provide us with some details on how to reproduce the error? Is it possible to share with us a PyMod session (.pmse file)? Is Modeller working properly with other files?

Thanks,
Alessandro

**Comment by biotech70** [comment]
Modeller gives error to run other files. Of course, I solved the problem by installing pymol using conda.

**Comment by paiardin** [comment]
Glad to know that you were able to solve the problem!
