### ISSUE TITLE
Bio.SubsMat removed from latest Biopython

### ISSUE THREAD

**Issue by JarrettSJohnson** [pymodproject/pymod#11]
`Bio.SubsMat` has been deprecated for a while and now has seemingly been removed for Biopython 1.8.
I believe that Biopython now recommends to use `Bio.Align.substitution_matrices` in its place for getting sub mat data.

**Comment by SerenaRosi** [comment]
Dear JarrettSJohnson,
thank you for your interest in Pymod 3.

This issue has now been solved. 

Best,
Serena
