### ISSUE TITLE
Modeller conda installation not working on multiple pymol versions

### ISSUE THREAD

**Issue by jhh1492** [pymodproject/pymod#13]
Hey... guessing this is similiar issue to DockingPie, no matter the pymol version I use the installation box for modeller says this version of pymol doesnt have conda, even if I used Conda to install that pymol

Easy way to manually add modeller not involving the GUI by chance? 

Thanks

**Comment by irisdisilverio** [comment]
1. INSTALL MODELLER in the same ENV of PyMOL
conda install -c salilab modeller 
or 
conda config --add channels salilab
conda install modeller 

2. ADD A MODELLER KEY 
edit the license file in /path_to_your_pymol-env/lib/modeller-10.5/modlib/modeller/config.py
by replacing XXXX with your MODELLER licence key 

3. Check that PyMOL can import the modeller module
open PyMOL and type in the command input area: import modeller
If you don't get errors, then you will be able to use it in PyMod/PyMOL 

Best, 
Iris

**Comment by jhh1492** [comment]
Thanks so much Iris that did the trick, Quick question, how do you retain the coloring of aligned sequences after exporting alignment and/or session? When I export my alignments the coloring (by AA type) dissapears

**Comment by jhh1492** [comment]
Keeping open as I dont know if it will be seen or send you notification, will close issue once I know youve seen it! Thanks for all yall do for us aspiring bioinformatics peoples!!

**Comment by irisdisilverio** [comment]
I'm glad it worked!
Regarding your question, if you have an alignment and you have colored the sequences by residue type, you can save the PyMod3 session (.pmse) from File > Sessions > Save. 
In this way, you will be able to view the coloring again every time you open the session on PyMod3 (File > Sessions > Open). 

Best,
Iris
