### ISSUE TITLE
homology modelling error

### ISSUE THREAD

**Issue by gardee11** [pymodproject/pymod#14]
while running homology modelling with "create new disulfide" option, I encountered this:
Pymod has encountered an unknown error in the modelling session: 'No such residue: "9"; did you mean "9:A" ?'
this refer to Cys9 on the sequence which I am trying to form a disulfide with another Cys residue
how do I resolve this? thanks

**Comment by SerenaRosi** [comment]
Hello,

This kind of error usually comes from MODELLER and is often related to an issue with the input. Please check for any possible errors involving that cysteine residue. If the problem persists, could you provide additional details about the input you are using?

Thanks,
Serena
